server:
  port: 80
spring:
  application:
    name: Gateway-server
  datasource:
    url: jdbc:mysql://39.105.89.185:3306/ShaunaIsComing
    username: root
    password: zxf1023778132
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:28001/eureka/
  instance:
    instance-id: Gateway-server
    prefer-ip-address: true
    ip-address: 127.0.0.1

#ip-address: 106.52.31.207把这个服务部署在腾讯云上！

zuul:
  routes:
    primary:
      serviceId: Primary-server
      path: /
    fs:
      serviceId: FS-server
      path: /shaunafs/**
    login:
      serviceId: Login-server
      path: /login/**
    regist:
      serviceId: Regist-server
      path: /regist/**
    uaa:
      serviceId: UAA-server
      path: /uaa/**
    primary2:
      serviceId: Primary-server
      path: /primary/**
  sensitive-headers:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 10000

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000