server:
  port: 28000
spring:
  application:
    name: Primary_server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:28001/eureka/
  instance:
    instance-id: Primary_server
    prefer-ip-address: true