server:
  port: 28000
spring:
  application:
    name: Primary-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:28001/eureka/
  instance:
    instance-id: Primary-server
    prefer-ip-address: true
    ip-address: 106.52.31.207

        #ip-address: 106.52.31.207把这个服务部署在腾讯云上！