server:
  port: ${primaryPort}
spring:
  application:
    name: Primary-server

eureka:
  client:
    service-url:
      defaultZone: http://${eurekaIp}:${eurekaPort}/eureka/
  instance:
    instance-id: Primary-server
    prefer-ip-address: true
    ip-address: ${primaryIp}

        #ip-address: 106.52.31.207把这个服务部署在腾讯云上！