server:
  port: 28002
spring:
  application:
    name: UAA-server
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:mysql://39.105.89.185:3306/ShaunaIsComing
    username: root
    password: zxf1023778132
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://106.52.31.207:28001/eureka/
  instance:
    instance-id: UAA-server
    prefer-ip-address: true
    ip-address: 106.52.31.207

    #ip-address: 106.52.31.207把这个服务部署在腾讯云上！