server:
  port: ${uaaPort}
spring:
  application:
    name: UAA-server
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: ${dbUrl}
    username: ${dbUsername}
    password: ${dbPassword}
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://${eurekaIp}:${eurekaPort}/eureka/
  instance:
    instance-id: UAA-server
    prefer-ip-address: true
    ip-address: ${uaaIp}

    #ip-address: 106.13.74.175把这个服务部署在腾讯云上！