server:
  port: 28006
spring:
  application:
    name: ShaunaCode-server

eureka:
  client:
    service-url:
      defaultZone: http://106.52.31.207:28001/eureka/
  instance:
    instance-id: ShaunaCode-server
    prefer-ip-address: true
    ip-address: 8.131.57.153

#ip-address: 8.131.57.153把这个服务部署在阿里云上！


