server:
  port: ${codePort}
spring:
  application:
    name: ShaunaCode-server

eureka:
  client:
    service-url:
      defaultZone: http://${eurekaIp}:${eurekaPort}/eureka/
  instance:
    instance-id: ShaunaCode-server
    prefer-ip-address: true
    ip-address: ${codeIp}

#ip-address: 8.131.57.153把这个服务部署在阿里云上！


