server:
  port: 80
spring:
  application:
    name: Gateway_server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:28001/eureka/
  instance:
    instance-id: Gateway_server
    prefer-ip-address: true

zuul:
  routes:
    primary:
      serviceId: Primary_server
      path: /**
    fs:
      serviceId: FS_server
      path: /shaunafs/**
    login:
      serviceId: Login_server
      path: /login/**
    regist:
      serviceId: Regist_server
      path: /regist/**
    uaa:
      serviceId: UAA_server
      path: /uaa/**
