server:
  port: 28001

eureka:
  instance:
    hostname: 106.52.31.207
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/