server:
  port: 28005
spring:
  application:
    name: FS-server

eureka:
  client:
    service-url:
      defaultZone: http://106.52.31.207:28001/eureka/
  instance:
    instance-id: FS-server
    prefer-ip-address: true
    ip-address: 39.105.89.185

#ip-address: 39.105.89.185把这个服务部署在阿里云上！