server:
  port: ${registPort}
spring:
  application:
    name: Regist-server
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: ${dbUrl}
    username: ${dbUsername}
    password: ${dbPassword}
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    username: ${emailUserName}
    password: ${emailPassword}
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://${eurekaIp}:${eurekaPort}/eureka/
  instance:
    instance-id: Regist-server
    prefer-ip-address: true
    ip-address: ${registIp}

#ip-address: 106.13.74.175把这个服务部署在阿里云上！


